apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v3wb9a0e5-python 
  janus-idp.io/tekton: v3wb9a0e5-python
  backstage.io/kubernetes-id: v3wb9a0e5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v3wb9a0e5-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml